"land_anvendelse":
  "Løvtræ": nature
  "Blandet": nature
  "Sandklit": nature
  "Dyrkede afgrøder på marker": agriculture
  "Lav bebyggelse": ignore
  "Afgræssede marker": agriculture
  "Skov": nature
  "Braklagte marker": agriculture
  "Sø": nature
  "Vådområde": nature
  "Sommerhusområde skov": sommerhus
  "Sommerhusområde": sommerhus
  "Andre": verify
  "Hede": nature
  "Sportsanlæg": ignore
  "Råstofområde": ignore
  "Gartneri": ignore
  "Nåletræ": nature
  "Kratbevoksning": nature
  "Erhverv": verify
  "Bykerne": culture
  "Energiforsyningsanlæg": verify
  "Militært anlæg": verify
  "Høj bebyggelse": verify
  "Lufthavn": verify
  "Affaldsanlæg": verify

"land_beskyttnatur_flade":
  "Beskyttet natur": nature

"land_frednatpark":
  "Fredet område": nature
  "Bekendtgørelsesfredning": nature
  "Naturnationalpark": nature
  "Naturpark": nature
  "Nationalpark": nature

"land_vaerdifuld":
  "Værdifuldt kulturmiljø": culture
  "Bevaringsværdig landskab": culture
  "Kulturhistorisk bevaringsværdi": culture
  "Naturbeskyttelsesområde": nature