"land_beskyttnatur_linje":
  "Beskyttet vandløb": ignore

"rute_anden":
  "Bilrute": ignore

"rute_cykel":
  "Cykelrute": ignore

"rute_vandre":
  "Vandrerute": ignore

# "vej_basislinje" # currently gitignored

"vej_hastighedsgraense":
  "80.0": ignore
  "70.0": ignore
  "60.0": ignore
  "30.0": ignore
  "40.0": ignore
  "20.0": ignore
  "50.0": ignore
  "10.0": ignore
  "90.0": ignore
  "100.0": ignore
  "110.0": ignore
  "300.0": ignore

"vej_myndighed":
  "Privat fællesvej": ignore
  "Off. kommunevej": ignore
  "Privat vej": ignore
  "Off. statsvej": ignore
  "Udlagt priv. fælles": ignore
  "Almen vej": ignore

# "vej_type" # currently gitignored