name: knupu
channels:
  - conda-forge
  - conda
  - defaults
dependencies:
  - python
  - pip
  - jupyter
  - jupyterlab
  - ipykernel
  - ipywidgets
  - numpy
  - pandas
  - shapely
  - geopandas 
  - osmnx
  - networkx
  - contextily
  - pyyaml
  - owslib
  - tqdm
  - qgis
  - folium
  - pyarrow
  - pyogrio
  - rasterio
  # - geojson
  - pip:
    - git+https://github.com/uscuni/sgeop.git