"facilit_indkoeb":
  "supermarked": service
  "bager": service
  "kiosk": service
  "slagter": service
  "Lokale smagsoplevelser": service
  "tankstation": service
  "fisk": service

"facilit_overnatning":
  "Bed & Breakfast": service
  "Hotel": service
  "Campingplads": service
  "Slot/Herregård": service
  "Vandrehjem": service
  "Feriecenter": service
  "Kro": service

"facilit_rasteplads":
  "Bænk": facility
  "Picnicbord": facility
  "Legeplads": facility
  "Borde-bænke/Picnic": facility
  "Tørvejrsrum/Madpakkehus": facility
  "Naturlegeplads": facility
  "Vandlegeplads": facility

"facilit_service": 
  "Toilet": facility
  "Drikkevand": facility
  "Cykelhandler": facility
  "Vandpost": facility
  "Cykeludlejere": facility
  "Cykelservice": facility
  "Cykelpumpestation/-servicepost": facility
  "Turistkontor": service

"land_besoegs":
  "Museum": poi
  "Forlystelsespark": poi
  "Dyrepark, zoo": poi
  "Dyrepark": poi
  "Anden seværdighed": poi
  "Frilandsmuseum": poi
  "Aboret, blomsterpark o.l.": poi

"land_fortid":
  "Gravhøj": poi
  "Vold eller voldsted": poi
  "Langdysse": poi
  "Jættestue": poi
  "Fortidsminde/ruin": poi
  "Skanse": poi
  "Ruin": poi
  "Batteri": poi
  "Dysse": poi
  "Runddysse": poi
  "Andet historisk anlæg": poi
  "Fæstningsanlæg": poi
  "Oldtidsvej": poi
  "Vikingeborg": poi
  "Oldtidsminde": poi

"land_landemaerke":
  "Kirke": poi
  "Fyrtårn": poi
  "Vejrmølle": poi
  "Herregård": poi
  "Slot": poi

"land_udflugt":
  "Udsigtspunkt": poi
  "Naturområde": poi
  "Fugletårn/Udsigtstårn": poi
  "Badestrand/-sted": poi
  "Blå Flag strand": poi
  "Badepunkt": poi
  "Badevandsflag": poi